server:
  port: 8080

#spring actuator services
management:
  endpoints:
    enabled-by-default: true

logging:
  level:
    org.springframework.web: debug
  file: app.log

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true



