server:
  port: 8080

#spring actuator services
management:
  endpoints:
    enabled-by-default: true

logging:
  level:
    org.springframework.web: debug
    org.springframework.jdbc.datasoruce: debug
  file: app.log

spring:
  security:
    user:
      name: admin
      password: secret
  jpa:
    hibernate:
      ddl-auto: update # auto create schema
    properties: # for log
      show_sql: true
      format_sql: true



